SELECT
    SESSION_ID AS SESSION_ID,
    ITEM_NAME AS ITEM_NAME,
    CAST(PRICE_PER_UNIT AS NUMERIC(10,2)) AS PRICE_PER_UNIT,
    CAST(ITEM_VIEW_AT AS TIMESTAMP) AS ITEM_VIEW_AT,
    CAST(ADD_TO_CART_QUANTITY AS INTEGER) AS ADD_TO_CART_QUANTITY,
    CAST(REMOVE_FROM_CART_QUANTITY AS INTEGER) AS REMOVE_FROM_CART_QUANTITY

FROM {{ source('web', 'item_views') }}